apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-production
resources:
  - ../../base
commonLabels:
  environment: production
images:
  - name: ghcr.io/mlops-project/mlops-api
    newName: ghcr.io/mlops-project/mlops-api
    newTag: production
patches:
  - path: deployment-patch.yaml
