apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-api-config
  labels:
    app: mlops-api
data:
  MLFLOW_TRACKING_URI: "http://mlflow.mlops.svc.cluster.local:5000"
  MLFLOW_MODEL_NAME: "churn_model"
  RELOAD_INTERVAL: "60"
  LOG_LEVEL: "info"
